version: "3.5"
services:
  redis:
    image: redis
    ports:
        - 6379:6379
    container_name: working-redis

  eventstore:
    image: eventstore/eventstore
    ports:
        - 2113:2113
        - 1113:1113
    container_name: working-eventstore

  rabbit:
    image: rabbitmq:3-management
    ports:
        - 15672:15672
        - 5672:5672
    container_name: working-rabbit